theme: jekyll-theme-cayman

github:
  is_project_page: false

title: My SOPINE A64 Cluster Ventures
description: Building and running a cluster of SOPINE A64 compute modules on a Pine64 Clusterboard.
